baseURL = '/'
title = '@George@RCsocial.net'
languageCode = 'en-us'

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"

[taxonomies]
  category = "Posts"

[[menu.main]]
  name = "Return to RCsocial.net"
  url = "https://RCsocial.net"
  weight = 10
